//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVCarStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int KhuyenMaiID { get; set; }
        public string MaKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> PhanTramGiamGia { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> ApDungChoTatCa { get; set; }
    }
}
